/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author WELCOME
 */
import java.awt.CardLayout;
public class Admin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin.class.getName());

    /**
     * Creates new form AdminLogin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        SignUp = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        AdminDashboard = new javax.swing.JPanel();
        DashNav = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        DashBoardBtn = new javax.swing.JLabel();
        ManageTeamBtn = new javax.swing.JLabel();
        ManagePlayer = new javax.swing.JLabel();
        BookingBtn = new javax.swing.JLabel();
        ScheduleBtn = new javax.swing.JLabel();
        AnnouncementBtn = new javax.swing.JLabel();
        MainDash = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TeamManagement = new javax.swing.JPanel();
        DashNav2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        DashBoardBtn1 = new javax.swing.JLabel();
        ManagePlayer1 = new javax.swing.JLabel();
        BookingBtn1 = new javax.swing.JLabel();
        ScheduleBtn1 = new javax.swing.JLabel();
        AnnouncementBtn1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        MainDash2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1311, 720));
        setSize(new java.awt.Dimension(1310, 720));
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.CardLayout());

        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SimSun", 0, 48)); // NOI18N
        jLabel2.setText("Login");

        jTextField2.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jTextField2.setBorder(new javax.swing.border.MatteBorder(null));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel4.setText("Username");

        jPasswordField1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jPasswordField1.setBorder(new javax.swing.border.MatteBorder(null));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        LoginBtn.setBackground(new java.awt.Color(51, 51, 51));
        LoginBtn.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(204, 204, 204));
        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel5.setText("New User ?");

        SignUp.setBackground(new java.awt.Color(239, 239, 239));
        SignUp.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        SignUp.setForeground(new java.awt.Color(0, 102, 204));
        SignUp.setText("Sign Up");
        SignUp.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SignUp))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jPasswordField1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SignUp))
                .addGap(59, 59, 59))
        );

        Login.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 490, 530));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/football.jpg"))); // NOI18N
        Login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(Login, "card2");

        AdminDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashNav.setBackground(new java.awt.Color(0, 102, 102));
        DashNav.setMinimumSize(new java.awt.Dimension(220, 720));
        DashNav.setLayout(new java.awt.CardLayout());

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setMinimumSize(new java.awt.Dimension(220, 720));

        jLabel7.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("volta.");

        DashBoardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ClickedDashboard.png"))); // NOI18N

        ManageTeamBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/UnclickedManageTeam-preview.png"))); // NOI18N

        ManagePlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/UnclickedManagePlayer.png"))); // NOI18N

        BookingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/UnclickedBooking.png"))); // NOI18N

        ScheduleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/UnclickedSchedule.png"))); // NOI18N

        AnnouncementBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/UnclickedAnnouncement.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(ManagePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DashBoardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManageTeamBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ScheduleBtn)
                            .addComponent(AnnouncementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(DashBoardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ManageTeamBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManagePlayer)
                .addGap(18, 18, 18)
                .addComponent(BookingBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScheduleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnnouncementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        ManageTeamBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                System.out.print("Button clicked");
                // Get the CardLayout from jPanel1
                CardLayout cardLayout = (CardLayout) jPanel1.getLayout();

                // Switch to the AdminDashboard card
                cardLayout.show(jPanel1, "card4");
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                ManageTeamBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
        });

        DashNav.add(jPanel5, "card2");

        AdminDashboard.add(DashNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 720));

        MainDash.setLayout(new java.awt.CardLayout());

        jLabel6.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel6.setText("Welcome Back Shaira!");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ProfileIcon.png"))); // NOI18N
        jLabel8.setText(".");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 574, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(581, Short.MAX_VALUE))
        );

        MainDash.add(jPanel6, "card2");

        AdminDashboard.add(MainDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1110, 720));

        jPanel1.add(AdminDashboard, "card3");
        AdminDashboard.getAccessibleContext().setAccessibleParent(AdminDashboard);

        TeamManagement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashNav2.setBackground(new java.awt.Color(0, 102, 102));
        DashNav2.setLayout(new java.awt.CardLayout());

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setMinimumSize(new java.awt.Dimension(220, 720));

        DashBoardBtn1.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        DashBoardBtn1.setForeground(new java.awt.Color(0, 51, 51));
        DashBoardBtn1.setText("volta.");

        ManagePlayer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/UnclickedManagePlayer.png"))); // NOI18N

        BookingBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/UnclickedBooking.png"))); // NOI18N

        ScheduleBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/UnclickedSchedule.png"))); // NOI18N

        AnnouncementBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/UnclickedAnnouncement.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/UnclickedDashboard.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ClickedManageTeam.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(ManagePlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DashBoardBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookingBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ScheduleBtn1)
                            .addComponent(AnnouncementBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(DashBoardBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManagePlayer1)
                .addGap(18, 18, 18)
                .addComponent(BookingBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScheduleBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnnouncementBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        DashNav2.add(jPanel7, "card2");

        TeamManagement.add(DashNav2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 720));

        MainDash2.setLayout(new java.awt.CardLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ProfileIcon.png"))); // NOI18N
        jLabel11.setText(".");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(939, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel11)
                .addContainerGap(581, Short.MAX_VALUE))
        );

        MainDash2.add(jPanel10, "card2");

        TeamManagement.add(MainDash2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1110, 720));

        jPanel1.add(TeamManagement, "card4");

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1310, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // Get the CardLayout from jPanel1
    CardLayout cardLayout = (CardLayout) jPanel1.getLayout();
    
    // Switch to the AdminDashboard card
    cardLayout.show(jPanel1, "card3");
    
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminDashboard;
    private javax.swing.JLabel AnnouncementBtn;
    private javax.swing.JLabel AnnouncementBtn1;
    private javax.swing.JLabel BookingBtn;
    private javax.swing.JLabel BookingBtn1;
    private javax.swing.JLabel DashBoardBtn;
    private javax.swing.JLabel DashBoardBtn1;
    private javax.swing.JPanel DashNav;
    private javax.swing.JPanel DashNav2;
    private javax.swing.JPanel Login;
    private javax.swing.JToggleButton LoginBtn;
    private javax.swing.JPanel MainDash;
    private javax.swing.JPanel MainDash2;
    private javax.swing.JLabel ManagePlayer;
    private javax.swing.JLabel ManagePlayer1;
    private javax.swing.JLabel ManageTeamBtn;
    private javax.swing.JLabel ScheduleBtn;
    private javax.swing.JLabel ScheduleBtn1;
    private javax.swing.JToggleButton SignUp;
    private javax.swing.JPanel TeamManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
